version: '3.8'
services:
  postgres:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: root
      POSTGRES_DB: cqrs
    ports:
      - '2345:5432'
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      DB_HOST: postgres
      DB_NAME: cqrs
      DB_USER: root
      DB_PORT: 5432
    depends_on:
      - postgres
