version: '3.9'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
  api:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"