version: "3.9"
services: 
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    volumes: 
      - .:/app
    depends_on: 
      - mysql_server
  mysql_server:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=cqrs
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - .:/app
    